Loading pretrained model
Fetching 17 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 236103.21it/s]
Loading datasets
Traceback (most recent call last):
  File "/Users/tristan/AI/DataCreation/CyberLLMInstruct/.venv/bin/mlx_lm.lora", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/tristan/AI/DataCreation/CyberLLMInstruct/.venv/lib/python3.13/site-packages/mlx_lm/lora.py", line 349, in main
    run(types.SimpleNamespace(**args))
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tristan/AI/DataCreation/CyberLLMInstruct/.venv/lib/python3.13/site-packages/mlx_lm/lora.py", line 312, in run
    train_set, valid_set, test_set = load_dataset(args, tokenizer)
                                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/tristan/AI/DataCreation/CyberLLMInstruct/.venv/lib/python3.13/site-packages/mlx_lm/tuner/datasets.py", line 305, in load_dataset
    raise ValueError(
        "Training set not found or empty. Must provide training set for fine-tuning."
    )
ValueError: Training set not found or empty. Must provide training set for fine-tuning.
